version: "3.9"

services:
  detector:
    build: ./services/detector
    env_file: ./.env
    volumes:
      - ./common:/home/common
      - ./models:/home/models
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  encoder:
    build: ./services/encoder
    env_file: ./.env
    volumes:
      - ./common:/home/common
      - ./models:/home/models
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
