version: '3.9'

volumes:
  huggingface_cache:
    external: false

services:
  pushgateway:
    image: prom/pushgateway:v1.6.0
    container_name: svr_mp_pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091

  detector:
    build:
      context: .
      dockerfile: ./services/detector/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./models:/home/models
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  encoder:
    build:
      context: .
      dockerfile: ./services/encoder/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - huggingface_cache:/root/.cache/huggingface/hub/
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
